name: Custom GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download required files
      run: |
        # Replace these URL placeholders with the actual download links
        curl -L -o SnapEnhance.apk ${{ secrets.SNAP_ENHANCE_APK_URL }}
        curl -L -o Snap.apk ${{ secrets.SNAP_APK_URL }}
      env:
        SNAP_ENHANCE_APK_URL: ${{ secrets.SNAP_ENHANCE_APK_URL }}
        SNAP_APK_URL: ${{ secrets.SNAP_APK_URL }}

    - name: Run the command
      run: |
        java -jar lspatch.jar -m SnapEnhance.apk -f -l 2 -v Snap.apk

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Snap-360-lspatched.apk
        path: ./Snap-360-lspatched.apk

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: Snap-360-lspatched.apk
        tag_name: v0.0
